# Generated by Django 4.0.6 on 2022-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
