# Generated by Django 4.0.6 on 2022-07-26 19:45

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0003_alter_user_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='order',
            name='date_picked_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 26, 19, 44, 39, 279984, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_ready',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rug',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
