# Generated by Django 4.0.6 on 2022-07-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0005_alter_order_date_picked_up_alter_order_date_placed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_picked_up',
            new_name='date_completed',
        ),
    ]
