# Generated by Django 4.0.6 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0006_rename_date_picked_up_order_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='user', to='rugs_app.rug'),
        ),
    ]
