# Generated by Django 4.0.6 on 2022-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0008_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails_new_rugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_emails_order_updates',
            field=models.BooleanField(default=True),
        ),
    ]
