# Generated by Django 4.0.6 on 2022-07-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0009_user_receive_emails_new_rugs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_placed']},
        ),
        migrations.AlterModelOptions(
            name='rug',
            options={'ordering': ['-date_created']},
        ),
    ]
