# Generated by Django 4.0.6 on 2022-12-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0010_alter_order_options_alter_rug_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rug_count',
            field=models.IntegerField(null=True),
        ),
    ]
