# Generated by Django 4.0.6 on 2022-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs_app', '0011_order_rug_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rug_count',
            field=models.IntegerField(),
        ),
    ]
